version: '3.8'
services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: coc # Optional: give it a specific name
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coc # Change this
      POSTGRES_PASSWORD: coc_rule # Change this
      POSTGRES_DB: rules # Change this
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data: